[book]
title = "Forgotten Bits: A Programmer's Guide to SE + AI Wisdom"
authors = ["Tim Menzies"]
language = "en"
multilingual = false
src = "."  # Use current directory for markdown files

[build]
build-dir = "../../4gotn.github.io"

